// padala.law — Complete exam content database
// All content from Paper 1-5 with case laws, model answers, and problem solutions

const PAPERS = [
  {
    id: "property", title: "Property Law", subtitle: "Transfer of Property Act & Easements Act",
    color: "#1D9E75", icon: "1",
    topics: [
      { title: "Transfer of Property — Definition & General Principles", type: "Part B: 10m",
        content: "**Section 5 of the Transfer of Property Act** defines transfer of property as an act by which a living person conveys property, in present or in future, to one or more other living persons, or to himself and one or more other living persons. The phrase 'living person' includes a company or association or body of individuals, whether incorporated or not.\n\n**What Cannot Be Transferred (Section 6):**\n\n**(a) Spes Successionis:** The chance of an heir-apparent succeeding to an estate cannot be transferred. A son cannot transfer his expected share in father's property during father's lifetime. This is a mere expectancy, not a present right.\n\n**(b) Right of re-entry:** Cannot be transferred to anyone except the owner of the property affected.\n\n**(c) Easement apart from dominant heritage:** An easement cannot be separated and transferred independently of the dominant heritage.\n\n**(d) Restricted interest:** An interest restricted in enjoyment to the owner personally cannot be transferred.\n\n**(e) Right to future maintenance:** Cannot be transferred. However, arrears of maintenance CAN be transferred as they have already accrued.\n\n**(f) Mere right to sue:** Cannot be transferred unless incidental to property.\n\n**Condition Restraining Alienation (Section 10):** A condition absolutely restraining the transferee from parting with or disposing of his interest is VOID. However, a partial restraint on alienation may be valid if reasonable. For example, a condition requiring consent of a named person before sale is a partial restraint and is valid.\n\n**Condition Restraining Enjoyment (Section 11):** Where an absolute interest is created but the terms direct it shall be enjoyed in a particular manner, the transferee can dispose of it as if there were no such direction. A condition repugnant to the nature of the interest created is void.\n\n**Rule Against Perpetuity (Section 14):** No transfer can create an interest which takes effect after the lifetime of one or more persons living at the date of transfer plus the minority of some person who shall be in existence at the expiration of that period.\n\n**Transfer to Unborn Person (Section 13):** Property may be transferred for the benefit of an unborn person provided: (i) a prior life interest is created in favour of a living person, (ii) the transfer to the unborn person encompasses the whole remaining interest, and (iii) no partial interest can be created.",
        cases: [
          { name: "Syed Mohd. Baksh v. Fakhr Jahan (1932)", point: "Privy Council held spes successionis is a mere possibility and cannot be transferred under Section 6(a)." },
          { name: "Rosher v. Rosher (1884)", point: "Condition requiring consent before sale is a partial restraint and valid — not an absolute restraint under Sec. 10." },
          { name: "Bhagwan Dass v. Jiwan Lal", point: "Condition not to sell for 20 years held to be partial restraint and valid, not absolute." },
          { name: "Mulraj v. Murti Raghonathji (1967)", point: "SC: right to manage temple is restricted interest personally attached to office holder, not transferable." }
        ]},
      { title: "Vested Interest & Contingent Interest", type: "Part A: 3m / Part B: 10m",
        content: "**Vested Interest (Section 19):** Where interest is created in favour of a person without specifying time, or to take effect on an event that MUST happen, the interest is vested immediately. Key: it vests at once even though enjoyment may be postponed. A vested interest is not defeated by the death of the transferee before obtaining possession.\n\n*Illustration:* A transfers property to B for life and then to C. C has a vested interest from the moment of transfer because B's death is certain. Even if C dies before B, C's heirs get the property.\n\n**Contingent Interest (Section 21):** Where interest depends on an UNCERTAIN event, it is contingent. Does not vest until condition is fulfilled. If condition fails, interest fails completely.\n\n*Illustration:* A transfers to B if B passes the law examination. B's interest is contingent — it depends on an uncertain event.\n\n**Key Differences:**\n(1) Nature of event: Vested = certain; Contingent = uncertain\n(2) Transferability: Both transferable, but vested more valuable\n(3) Effect of death: Vested passes to heirs; Contingent may fail\n(4) Heritable: Vested always heritable; Contingent only if not personal survival\n(5) Present right: Vested gives present right of future enjoyment; Contingent gives no present right",
        cases: [
          { name: "Rajes Kanta Roy v. Santi Debi (1957)", point: "SC: if the condition must happen → vested; if it may or may not happen → contingent." },
          { name: "Gyan Chand v. Kamla Devi", point: "The test is the intention of the parties and the language of the instrument." }
        ]},
      { title: "Sale (Sections 54-57)", type: "Part B: 10m",
        content: "**Definition (Section 54):** Sale is a transfer of ownership in exchange for a price paid or promised or part-paid and part-promised. Price means money consideration.\n\n**Essential Features:** (1) Transfer of ownership (not just possession), (2) Consideration must be money (if property, it's exchange; if nothing, it's gift), (3) Must be by registered instrument for property ≥ Rs.100, (4) Parties must be competent.\n\n**Modes of Sale:** For tangible immovable property ≥ Rs.100: ONLY by registered instrument. For < Rs.100: by registered instrument or by delivery of property. For intangible immovable property: only by registered instrument.\n\n**Contract for Sale vs Sale (Sec. 54, Para 3):** An agreement to sell does NOT create any interest in or charge on the property. Only a completed registered sale deed transfers ownership.\n\n**Doctrine of Part Performance (Sec. 53A):** Protects a buyer who has: (i) taken possession, or (ii) made improvements, or (iii) done any act in furtherance of the contract, AND is willing to perform his part. The seller cannot enforce rights inconsistent with the contract. It is a SHIELD not a SWORD — defence only, cannot sue for title.\n\n**Registration (Sec. 17, Registration Act 1908):** Sale of immovable property ≥ Rs.100 MUST be registered. Non-registration: document inadmissible as evidence of transaction, but may be used for collateral purpose.\n\n**Rights/Duties of Seller (Sec. 55):** Disclose material defects, produce title documents, answer relevant questions, execute proper conveyance, pay charges, give possession. Seller has charge on property for unpaid price.\n\n**Rights/Duties of Buyer (Sec. 55):** Disclose facts materially increasing value, pay purchase money, bear loss after completion.",
        cases: [
          { name: "Suraj Lamp & Industries v. State of Haryana (2012)", point: "SC: GPA sales, agreement sales, and will transfers are NOT valid modes of transfer. Only registered sale deeds are valid." },
          { name: "Vidhyadhar v. Manikrao (1999)", point: "Seller has implied charge on property for unpaid purchase money under Sec. 55(4)(b)." },
          { name: "S.P. Chengalvaraya Naidu v. Jagannath (1994)", point: "SC: decree obtained by fraud or suppression is nullity and can be set aside." }
        ]},
      { title: "Mortgage — Six Types (Section 58)", type: "Part A: 3m / Part B: 10m",
        content: "**Definition (Section 58):** A mortgage is the transfer of an interest in specific immovable property for the purpose of securing payment of money advanced or to be advanced by way of loan. Transferor = mortgagor, transferee = mortgagee. Ownership does NOT pass — only an interest is transferred as security.\n\n**1. Simple Mortgage (58(b)):** No possession delivery. Mortgagor personally liable. Mortgagee can cause sale through COURT only. Cannot sell himself.\n\n**2. Mortgage by Conditional Sale (58(c)):** Ostensible sale with condition — on default sale becomes absolute, OR on payment sale becomes void. No possession delivery. Mortgagee must file foreclosure suit — sale does NOT become absolute automatically.\n\n**3. Usufructuary Mortgage (58(d)):** Possession DELIVERED. Mortgagee receives rents and profits. Key: mortgagee CANNOT sue mortgagor personally for mortgage money. Only remedy is to retain possession and recover from income.\n\n**4. English Mortgage (58(e)):** Most comprehensive. Property transferred ABSOLUTELY + personal liability to repay by certain date. Mortgagee re-transfers on repayment. Both personal liability AND property transfer.\n\n**5. Equitable Mortgage / Deposit of Title Deeds (58(f)):** In notified towns (Kolkata, Mumbai, Chennai etc.), delivery of title deeds with intent to create security. No mortgage deed or registration needed. Simplest form.\n\n**6. Anomalous Mortgage (58(g)):** Any combination not fitting above five categories.\n\n**Right of Redemption (Sec. 60):** Most fundamental right of mortgagor. Maxim: 'Once a mortgage, always a mortgage.' Cannot be clogged or fettered. Any condition restricting redemption is VOID.\n\n**Subrogation (Sec. 92):** Person with interest in mortgaged property who redeems the mortgage steps into mortgagee's shoes.\n\n**Marshalling (Sec. 81):** If owner mortgages A+B to X, then A to Y — Y can require X to satisfy from B first.\n\n**Contribution (Sec. 82):** Co-owners of mortgaged property contribute ratably to mortgage debt.",
        cases: [
          { name: "Noakes v. Rice (1902)", point: "House of Lords: condition requiring mortgagor to buy beer from mortgagee even after redemption was CLOG on equity of redemption — VOID." },
          { name: "Seth Ganga Dhar v. Shankar Lal (1958)", point: "SC: mortgage by conditional sale does NOT automatically become absolute sale on default. Foreclosure decree needed." },
          { name: "Ghulam Mohiuddin v. Ghulam Qadir", point: "Right of redemption subsists as long as mortgage subsists — any condition clogging it is void." }
        ]},
      { title: "Gift & Donatio Mortis Causa (Sections 122-129)", type: "Part B: 10m / Part C: 10m",
        content: "**Definition (Sec. 122):** Transfer of existing property, voluntarily, without consideration, by donor to donee. Acceptance must be during donor's lifetime while capable of giving.\n\n**Essentials:** (1) Existing property (future property cannot be gifted), (2) Voluntary transfer (free consent), (3) Without consideration, (4) Competent donor, (5) Any donee (including minor through guardian), (6) Acceptance during donor's lifetime.\n\n**How Effected (Sec. 123):** Immovable property: MUST be by registered instrument signed by donor, attested by 2 witnesses. Movable property: by registered instrument OR by delivery of possession (actual or constructive).\n\n**Onerous Gift (Sec. 127):** Gift of several things, some burdened — donee must accept all or none.\n\n**Revocation (Sec. 126):** Gift revocable ONLY if: (i) express agreement between donor and donee, (ii) for revocation on a specified event, (iii) event NOT dependent on donor's will, (iv) event actually happens. Gift CANNOT be revoked merely at donor's pleasure — such reservation makes the entire gift VOID.\n\n**Donatio Mortis Causa:** Gift in contemplation of death. Essentials: (i) made in apprehension of death from existing illness, (ii) donor actually dies of apprehended illness, (iii) possession delivered, (iv) conditional — revocable if donor recovers.\n\n**Indian Position:** Donatio mortis causa of IMMOVABLE property is NOT valid in India because Sec. 123 requires registered instrument. For movable property, it is recognized (delivery satisfies requirement).",
        cases: [
          { name: "Cain v. Moon (1896)", point: "English court laid down essentials of donatio mortis causa — contemplation of death, delivery, conditional on death." },
          { name: "Kashi Prasad v. Chhabi Nath (1936)", point: "Allahabad HC: donatio mortis causa of immovable property NOT recognized in India under Sec. 123." },
          { name: "K.S. Kariyappa v. N.P. Shadakshari", point: "Unregistered gift deed of immovable property is void — cannot be validated as donatio mortis causa." }
        ]},
      { title: "Lease (Sections 105-117)", type: "Part B: 10m",
        content: "**Definition (Sec. 105):** Transfer of right to enjoy immovable property for certain time, in consideration of rent/premium. Lessor retains ownership; only right to enjoy is transferred.\n\n**Essentials:** (1) Competent parties, (2) Immovable property, (3) Duration — certain time or perpetuity, (4) Consideration — rent or premium, (5) Transfer of right to enjoy (not ownership), (6) Acceptance by lessee.\n\n**Kinds:** (1) Fixed term — terminates automatically on expiry. (2) Periodic (month to month, year to year) — renews unless terminated by notice. (3) Perpetuity — continues forever. (4) Tenancy at will — terminable at will of either party. (5) Holding over (Sec. 116) — lessee stays after expiry, lessor accepts rent → new lease implied on same terms (except duration). (6) Tenancy by sufferance — tenant stays without consent after term ends.\n\n**Lessor's Duties (Sec. 108):** (a) Disclose material defects, (b) Put lessee in possession, (c) Allow quiet enjoyment.\n\n**Lessee's Duties (Sec. 108):** (a) Pay rent, (b) Maintain property (not commit waste), (c) Give notice of encroachments, (d) Use as prudent person would, (e) Not erect permanent structures without consent, (f) Not use for unlawful purposes, (g) Restore possession on termination.\n\n**Termination Notice (Sec. 106):** Agricultural/manufacturing: 6 months. Other purposes: 15 days. Notice must end with period of tenancy.",
        cases: [
          { name: "Raj Kumar v. Firm Nemi Chand (1981)", point: "SC: lease governed by agreed terms subject to TPA provisions. Purpose must be specified." }
        ]},
      { title: "Easement (Indian Easements Act, 1882)", type: "Part A: 3m / Part B: 10m",
        content: "**Definition (Sec. 4):** Right of owner/occupier of land (dominant heritage) to do or prevent something on another's land (servient heritage) for beneficial enjoyment of dominant heritage.\n\n**Essentials:** (1) Dominant and servient heritage — two different properties, (2) Must benefit the LAND not just the person, (3) Different owners, (4) Right to do or prevent something.\n\n**Kinds:** (1) **Continuous & Discontinuous:** Continuous = enjoyed without act of man (right of light). Discontinuous = requires act (right of way). (2) **Apparent & Non-apparent:** Apparent = visible signs (beaten path, window). Non-apparent = no visible sign. (3) **Positive & Negative:** Positive = doing something on servient land. Negative = preventing servient owner from doing something.\n\n**Acquisition:** (1) **By Grant** — express or implied. (2) **By Prescription (Sec. 15)** — 20 years peaceful, open, continuous, as-of-right enjoyment (30 years vs government). NOT by permission, secrecy, or force. (3) **By Necessity** — e.g., landlocked property gets way of necessity.\n\n**Termination (Sec. 37-47):** Dissolution of heritage, expiry, release, merger (both heritages same owner), abandonment, destruction, court decree, non-user for 20 years.\n\n**Easement vs Licence (Sec. 52):**\nEasement = right in rem (against world), runs with land, not revocable, requires two tenements, transferable, heritable.\nLicence = right in personam (personal), does not run with land, generally revocable, no two tenements needed, not transferable, dies with licensee.",
        cases: [
          { name: "Associated Hotels v. R.N. Kapoor (1959)", point: "SC: licence is permission to do what would otherwise be unlawful, creates no interest in property." },
          { name: "Radhakisan v. Shridhar (1960)", point: "SC: critical test is whether right benefits the land (easement) or the person (licence)." },
          { name: "Bellamy v. Sabine (1857)", point: "Lis pendens is based on necessity for administration of justice, not on notice." }
        ]},
      { title: "Lis Pendens, Election, Feeding the Grant & Covenants", type: "Part A: 3m / Part B: 10m",
        content: "**Lis Pendens (Sec. 52):** During pendency of suit involving right to immovable property, the property cannot be transferred so as to affect rights of other party. Transfer is NOT void but subject to suit outcome. Notice to transferee is IRRELEVANT — operates on principle of necessity for justice administration.\n\n**Doctrine of Election (Sec. 35):** When person professes to transfer another's property AND gives benefit to that owner — owner must CHOOSE: accept benefit + allow transfer, OR keep property + refuse benefit. Cannot approbate and reprobate.\n\n**Feeding the Grant by Estoppel (Sec. 43):** If person fraudulently or erroneously represents having title and transfers for consideration — and later actually acquires the property — earlier transfer becomes effective at option of transferee. Different from Sec. 6(a) which bars spes successionis. Sec. 43 operates where transferor makes representation of title.\n\n**Covenants:** Positive covenant (obligation to do something — build, repair) generally does NOT run with land. Negative covenant (restriction on use — not to build beyond height) DOES run with land and binds subsequent purchasers with notice. Section 40 TPA incorporates the rule in Tulk v. Moxhay.\n\n**Actionable Claims (Sec. 130):** Unsecured debt or claim to movable property not in possession. Transfer by instrument in writing signed by transferor. Notice to debtor advisable (fixes priority) but not mandatory for validity.",
        cases: [
          { name: "Jayaram Mudaliar v. Ayyaswami (1972)", point: "SC: Sec. 52 applies to ALL transfers during suit, whether transferee has notice or not." },
          { name: "Jumma Masjid v. Kodimaniandra (1962)", point: "SC: Sections 6(a) and 43 operate in different fields. Sec. 43 applies when transferor represents having title." },
          { name: "Tulk v. Moxhay (1848)", point: "Landmark: restrictive covenant binds subsequent purchasers with notice, even without privity of contract." }
        ]},
      { title: "Problem Questions — Property Law (Part C: 10m)", type: "Part C: 10m",
        content: "**Problem 1: Spes Successionis** — 'A son wants to transfer expected inheritance during father's lifetime.'\n**Answer:** Transfer is VOID under Sec. 6(a). Son has only spes successionis — mere expectancy, not present right. Father may dispose of property, disinherit son, or outlive son. (Syed Mohd. Baksh v. Fakhr Jahan)\n\n**Problem 2: Condition Restraining Alienation** — 'P sells to Q, condition: don't alienate without A's consent.'\n**Answer:** Condition is VALID. This is partial restraint (not absolute) under Sec. 10. Q is not entirely prohibited — can sell with consent. (Rosher v. Rosher)\n\n**Problem 3: Mortgage Accession** — 'A mortgages plot to B, later builds house on it. Is B entitled to house?'\n**Answer:** YES. Under Sec. 70, accessions/improvements to mortgaged property enure for benefit of mortgagee. House is accession to mortgaged plot.\n\n**Problem 4: Gift with Right to Revoke** — 'A gifts to B, reserving right to revoke at any time he pleases.'\n**Answer:** Gift is VOID. Under Sec. 126, revocation must be on specified event NOT dependent on donor's will. Donor's pleasure is not a valid event. No completed transfer exists.\n\n**Problem 5: Lis Pendens** — 'A sues B over estate. During suit, C (party) transfers to D without notice.'\n**Answer:** Transfer is NOT void but D takes subject to suit outcome. Under Sec. 52, lis pendens applies regardless of notice. D is bound by decree. (Jayaram Mudaliar v. Ayyaswami)\n\n**Problem 6: Easement by Prescription** — 'Person uses path across neighbour's land for 25 years.'\n**Answer:** YES, can claim easement by prescription under Sec. 15 — 25 years exceeds 20-year requirement. Must prove: peaceful, open, continuous, as-of-right (not by permission). If by neighbour's permission, it's a licence, not easement.\n\n**Problem 7: Donatio Mortis Causa** — 'A on deathbed gifts land to C which B (A's son) was to inherit.'\n**Answer:** INVALID. Two reasons: (1) A (son) has only spes successionis — Sec. 6(a) bars transfer. (2) Even as donatio mortis causa, immovable property requires registered deed under Sec. 123.",
        cases: []}
    ]
  },
  {
    id: "labour", title: "Labour Law", subtitle: "Trade Union Act | ID Act | Standing Orders Act",
    color: "#D85A30", icon: "2",
    topics: [
      { title: "Laissez Faire to Welfare State", type: "Part B: 10m",
        content: "**Laissez Faire:** French for 'let them do.' Minimal state intervention in economic affairs. During Industrial Revolution, workers treated as commodities — subsistence wages, 14-16 hour days, dangerous conditions, no protections. Child labour rampant. Doctrine of 'hire and fire' prevailed.\n\n**Problems:** Grossly unequal bargaining power. Workers had no choice but accept whatever terms employer offered. Led to: extremely low wages, unsafe conditions, child labour, no job security, social unrest.\n\n**Transition to Welfare State:** State recognized non-interference led to exploitation. Transition through stages: (1) Factory legislation (Factories Act 1881 in India), (2) Trade union recognition (TU Act 1926), (3) Social security legislation (ESI Act, PF Act, Gratuity Act), (4) Dispute resolution machinery (ID Act 1947).\n\n**Indian Constitution — Welfare State provisions:** Directive Principles (Part IV): Art. 39 (adequate livelihood), Art. 41 (right to work, education, public assistance), Art. 42 (just and humane conditions of work), Art. 43 (living wage, decent standard of life), Art. 43A (participation of workers in management).\n\n**International Labour Standards:** ILO (International Labour Organization) conventions adopted by India on various matters — hours of work, forced labour, freedom of association, minimum wage, social security.",
        cases: [
          { name: "Bangalore Water Supply v. A. Rajappa (1978)", point: "Justice Krishna Iyer discussed transformation from laissez faire to welfare state. Gave very wide definition of 'industry' — triple test." },
          { name: "Crown Aluminium Works v. Workmen (1958)", point: "SC: social justice underlies all labour legislation; fruits of progress must be equitably shared." }
        ]},
      { title: "Trade Union — Registration, Rights & Cancellation", type: "Part A: 3m / Part B: 10m / Part C: 10m",
        content: "**Definition (Sec. 2(h), Trade Unions Act, 1926):** Any combination, whether temporary or permanent, formed primarily for regulating relations between workmen and employers, or imposing restrictive conditions on trade or business. Includes federations.\n\n**Registration (Sec. 3-9):** 7+ members apply to Registrar with: copy of rules, member details, office-bearer details. Rules must provide for: name, objects, general fund purposes, membership list, minimum subscription (Re.1 rural, Rs.3 others), conditions for office-bearers, amendment procedure, dissolution manner.\n\n**Rights of Registered TU:** (1) **Immunity from civil suit (Sec. 18)** — no suit for acts done in furtherance of trade dispute (inducing breach of employment contract, interfering with trade). (2) **Immunity from criminal conspiracy (Sec. 17)** — agreements furthering trade union objects not criminal conspiracy. (3) **General Fund (Sec. 15)** — for salaries, legal proceedings, trade disputes, periodical publications. (4) **Political Fund (Sec. 16)** — separate fund, only from willing members, for political activities. (5) Right to amalgamate (Sec. 24), change name (Sec. 25), sue and be sued (Sec. 13).\n\n**Cancellation (Sec. 10):** Grounds: (a) Certificate by fraud/mistake, (b) Union ceased to exist, (c) Willful contravention of Act, (d) Membership below minimum. **2 months' notice** required. Opportunity to show cause. Appeal available.\n\n**Problems of Trade Unionism in India:** (1) Multiplicity of unions weakens bargaining, (2) Outside leadership — politicians dominate, (3) Political affiliation — unions as political instruments, (4) Inter-union rivalry, (5) Low membership in unorganized sectors, (6) Financial weakness.",
        cases: [
          { name: "All India Bank Employees' Assn. v. NIT (1962)", point: "SC upheld right to form unions under Art. 19(1)(c), subject to reasonable restrictions under Art. 19(4)." },
          { name: "Balmer Lawrie Workers' Union v. Balmer Lawrie (1985)", point: "Immunity under Sec. 17-18 extends to acts in furtherance of trade disputes, not unconnected criminal acts." }
        ]},
      { title: "Strike & Lockout", type: "Part A: 3m / Part B: 10m",
        content: "**Strike (Sec. 2(q), ID Act):** Cessation of work by employees acting in combination, or concerted refusal to work or accept employment. Forms: tool-down, pen-down, sit-down (dharana), go-slow, work-to-rule, hunger strike, sympathetic strike, general strike.\n\n**Lockout (Sec. 2(l)):** Temporary closing of workplace, suspension of work, or refusal to continue employing. Employer's counterpart to strike.\n\n**Is Strike a Fundamental Right?** NO. Art. 19(1)(c) guarantees right to form associations but SC held this does NOT include right to strike. Strike is a STATUTORY right under ID Act, subject to conditions and restrictions.\n\n**Statutory Limitations (Sec. 22-23):**\nSec. 22 (Public Utility Services): No strike without 14 days' notice. No strike within 14 days of notice. No strike during conciliation and 7 days after.\nSec. 23 (General): No strike during pendency of conciliation before Board, proceedings before Labour Court/Tribunal/National Tribunal, and 7 days after. No strike during operation of settlement or award.\n\n**Illegal Strikes (Sec. 24):** Strike commenced/continued in contravention of Sec. 22/23, or contrary to order under Sec. 10(3). **Consequences (Sec. 26):** Workers may lose wages, face imprisonment up to 1 month or fine up to Rs.50.\n\n**Go-slow:** Not defined in the Act but recognized by courts as more harmful than strike. Amounts to breach of contract of employment.",
        cases: [
          { name: "T.K. Rangarajan v. Govt. of Tamil Nadu (2003)", point: "SC: Government employees have NO fundamental, legal, or equitable right to strike." },
          { name: "B.R. Singh v. Union of India (1989)", point: "SC recognized strike as weapon of last resort in industrial context, but not absolute right." },
          { name: "Kameshwar Prasad v. State of Bihar (1962)", point: "SC struck down rule prohibiting demonstrations but did not declare unqualified right to strike." },
          { name: "All India Bank Employees' Assn. v. NIT (1962)", point: "SC: right to form unions under Art. 19(1)(c) does not include right to strike or collective bargaining." }
        ]},
      { title: "Collective Bargaining", type: "Part B: 10m",
        content: "**Definition:** Process of negotiation between employer and organized workers (union) about terms and conditions of employment. Cornerstone of industrial democracy.\n\n**Essential Characteristics:** (1) **Collective** — workers act through union, not individually. (2) **Bipartite** — two parties only, no third-party intervention (unlike conciliation/adjudication). (3) **Continuous** — ongoing relationship, not one-time event. (4) **Dynamic** — terms change with economic conditions. (5) **Industrial democracy** — workers' voice in determining conditions. (6) **Complementary** — seeks balance between employer profitability and worker welfare. (7) **Good faith** — genuine intent to reach agreement.\n\n**Merits:** (a) Promotes industrial peace, (b) Establishes fair wages/conditions by mutual agreement, (c) Strengthens trade unions, (d) Democratic method, (e) Flexibility — terms suit specific industries, (f) Reduces litigation, (g) Increases productivity.\n\n**Demerits:** (a) Multiplicity of unions weakens bargaining, (b) Outside leadership may pursue own agendas, (c) Power imbalance in surplus labour industries, (d) May lead to unreasonable demands, (e) Excludes unorganized workers, (f) Political interference, (g) No legal obligation to bargain in good faith in Indian law (unlike USA).\n\n**Structure of Bargaining:** Plant level → Industry level → National level. Recognition of bargaining agent is crucial — multiple unions create problems.",
        cases: [
          { name: "Karnal Leather Karamchari Sangathan v. Liberty Footwear (1989)", point: "SC recognized collective bargaining as essential feature of modern industrial relations." }
        ]},
      { title: "Industrial Disputes — Settlement Machinery", type: "Part B: 10m",
        content: "**Definition of Industrial Dispute (Sec. 2(k)):** Dispute between employers and workmen, connected with employment/non-employment/terms/conditions of labour.\n\n**Definition of Industry (Sec. 2(j)):** Very wide — any business, trade, undertaking, manufacture, calling of employers. **Triple Test (Bangalore Water Supply case):** (1) Systematic activity, (2) Organized by cooperation between employer and employee, (3) For production/distribution of goods and services.\n\n**Settlement Machinery — 7 Bodies:**\n\n**1. Works Committee (Sec. 3):** 100+ workmen establishments. Equal representatives. Consultative body for promoting good relations.\n\n**2. Conciliation Officer (Sec. 4):** Appointed by government to mediate. Proceedings within 14 days (extendable). Settlement = binding on both parties.\n\n**3. Board of Conciliation (Sec. 5):** Chairman (independent) + 2/4 members (equal representation). For complex disputes.\n\n**4. Court of Inquiry (Sec. 6):** Fact-finding body. Report within 6 months. Published for public information.\n\n**5. Labour Court (Sec. 7):** Judge of HC/DC with 7 years' experience. Adjudicates Second Schedule matters: standing orders, discharge/dismissal, illegality of strike/lockout.\n\n**6. Industrial Tribunal (Sec. 7A):** Similar qualifications. Second + Third Schedule: wages, hours, leave, bonus, retrenchment. Wider than Labour Court.\n\n**7. National Tribunal (Sec. 7B):** Disputes of national importance or affecting multiple states. HC judge qualifications.\n\n**Sec. 10 — Reference:** Government may refer to appropriate authority. Discretion must be judicial, not arbitrary.",
        cases: [
          { name: "Bangalore Water Supply v. A. Rajappa (1978)", point: "SC: triple test for 'industry.' Hospitals, educational institutions, charitable organizations can be industries." },
          { name: "Bombay Union of Journalists v. State of Bombay (1964)", point: "SC: government's power under Sec. 10 is not absolute, must be exercised reasonably." }
        ]},
      { title: "Lay-off, Retrenchment & Closure", type: "Part B: 10m",
        content: "**Lay-off (Sec. 2(kkk)):** Failure to give employment due to shortage of raw materials, breakdown of machinery, accumulation of stocks, natural calamity. **Compensation (Sec. 25C):** 50% of basic + DA. Max 45 days in 12 months. Workman must present himself daily. **Special (Chapter VB, Sec. 25M):** 100+ workmen establishments: prior government permission required.\n\n**Retrenchment (Sec. 2(oo)):** Termination of service for any reason OTHER than punishment. Excludes: voluntary retirement, superannuation, ill-health termination, contract non-renewal. **Conditions (Sec. 25F):** (a) 1 year continuous service, (b) 1 month written notice or wages in lieu, (c) 15 days' average pay per completed year of service (compensation), (d) Notice to government. **Last-come-first-go (Sec. 25G):** Last employed = first retrenched (unless good reason, which must be recorded). **Re-employment preference (Sec. 25H):** Retrenched workers get preference.\n\n**Closure (Sec. 2(cc)):** Permanent closing of place of employment. **Sec. 25FFA:** 60 days' notice to government and workmen. **Sec. 25O:** 100+ workmen: 90 days' prior government permission. Compensation same as retrenchment.\n\n**Sec. 25FFF — Compensation for closure:** Every workman with 1+ year continuous service entitled to retrenchment compensation.",
        cases: [
          { name: "Workmen of Subong Tea Estate v. Workmen (1964)", point: "SC: lay-off is temporary; retrenchment is permanent termination." },
          { name: "Hariprasad v. A.D. Divikar (1957)", point: "SC defined retrenchment widely as any termination by employer for any reason, other than punishment." }
        ]},
      { title: "Standing Orders & Domestic Enquiry", type: "Part B: 10m / Part C: 10m",
        content: "**Industrial Employment (Standing Orders) Act, 1946:** Requires employers in establishments with 100+ workmen to define employment conditions through Standing Orders. Purpose: certainty and uniformity.\n\n**Content (Schedule):** Classification of workmen, work hours, holidays, pay days, wage rates, shift working, attendance, leave conditions, termination requirements, misconduct and penalties, means of redress.\n\n**Certification Process:** (1) Submit draft to Certifying Officer within 6 months. (2) Officer sends to union/workmen for objections. (3) After hearing, officer certifies (with/without modifications). (4) Effective 30 days after authenticated copies sent. (5) Appeal to appellate authority within 30 days. Model Standing Orders (in Schedule) apply until certified.\n\n**Binding (Sec. 6):** Certified orders binding on BOTH employer and workmen.\n\n**Domestic Enquiry — Procedure:**\n(1) **Charge sheet** — clear, specific charges with reasonable time to reply (7-15 days)\n(2) **Written reply** by employee. If admits → enquiry may not be needed\n(3) **Impartial enquiry officer** — no personal bias or involvement\n(4) **Evidence** — both sides present evidence and witnesses\n(5) **Cross-examination** — employee's fundamental right\n(6) **Representation** — by co-worker (not generally by lawyer unless presenting officer is legally trained)\n(7) **Findings** — based on evidence on record only\n(8) **Show cause notice** — with proposed punishment\n(9) **Reasoned order** — by disciplinary authority\n(10) **Appeal** — if provided for\n\n**Defective enquiry → dismissal invalid.** Tribunal may: reinstate, direct fresh enquiry, or allow employer to justify before Tribunal (burden shifts to employer).\n\n**Sec. 33 (Prenatal/Postnatal control):** During proceedings: employer cannot alter conditions or dismiss without permission (prenatal) or prior approval (postnatal — Sec. 33(2)(b): can dismiss for connected misconduct but must pay 1 month's wages and get approval).",
        cases: [
          { name: "Delhi Cloth & General Mills v. Shambhu Nath Mukherjee", point: "SC: dismissal without proper domestic enquiry is violation of natural justice — order set aside." },
          { name: "Workmen of Firestone v. Management (1973)", point: "SC: Tribunal can permit employer to lead evidence to justify dismissal even if enquiry was defective." },
          { name: "State Bank of India v. N. Sundara Money (1976)", point: "SC: employee entitled to receive document copies and cross-examine witnesses. Denial vitiates enquiry." }
        ]}
    ]
  },
  {
    id: "company", title: "Company Law", subtitle: "Companies Act, 2013",
    color: "#534AB7", icon: "3",
    topics: [
      { title: "Company — Definition & Corporate Personality", type: "Part A: 3m / Part B: 10m",
        content: "**Definition:** A company is an artificial person created by law, having separate legal entity, perpetual succession, common seal (optional under 2013 Act), and limited liability. Under Sec. 2(20), company means a company incorporated under this Act or previous company law.\n\n**Essential Characteristics:**\n\n**(1) Separate Legal Entity:** Company is distinct from its members. Can own property, contract, sue, be sued in its own name. Members' debts are not company's debts and vice versa. Established in Salomon v. Salomon.\n\n**(2) Limited Liability:** Members' liability limited to unpaid amount on shares (company limited by shares) or guaranteed amount (company limited by guarantee).\n\n**(3) Perpetual Succession:** Company continues regardless of member changes — members may come and go, die or become insolvent, but company lives on. Only ends through winding up.\n\n**(4) Common Seal:** Company acts through its common seal. Documents under seal bind the company. Made optional under 2013 Act.\n\n**(5) Transferability of Shares:** Members can freely transfer shares (subject to articles). Gives liquidity to investment.\n\n**(6) Separate Management:** Board of Directors manages. Owners (shareholders) and managers (directors) are separate.\n\n**Distinction: Corporate vs Non-Corporate:**\nCompany = separate entity, limited liability, large membership, transferable shares, perpetual succession, mandatory registration.\nPartnership = no separate entity, unlimited liability, max 50/100 members, consent needed for transfer, dissolves on death/insolvency, registration optional.",
        cases: [
          { name: "Salomon v. Salomon & Co. (1897)", point: "House of Lords: company is separate legal person. Salomon owned 20,001 of 20,007 shares. Company's debts are not his debts. Most fundamental case." },
          { name: "Lee v. Lee's Air Farming (1961)", point: "Privy Council: owner-director can be employee of his own company — separate entities." },
          { name: "Macaura v. Northern Assurance (1925)", point: "Shareholder has no insurable interest in company's assets — property belongs to company." }
        ]},
      { title: "Corporate Veil — Lifting & Piercing", type: "Part B: 10m",
        content: "**Concept:** Corporate veil is the legal concept that company is separate from members. It shields shareholders from personal liability. But this veil is NOT absolute — courts lift it in certain circumstances.\n\n**Statutory Grounds:**\n(1) Reduction of membership below minimum and business continued for 6+ months — members personally liable.\n(2) Misrepresentation in prospectus — directors/promoters personally liable.\n(3) Misdescription of company name on instruments — officer personally liable.\n(4) Fraudulent trading (Sec. 339) — persons knowingly party to fraud personally responsible.\n(5) Failure to return application money within 78 days — directors jointly and severally liable.\n\n**Judicial Grounds:**\n(1) **Fraud/Improper conduct** — corporate form used to perpetrate fraud.\n(2) **Agency** — company acts as agent of members.\n(3) **Tax evasion** — corporate form used to evade tax.\n(4) **Enemy character** — determining true nationality during wartime.\n(5) **Sham/facade** — company is merely a device.\n(6) **Interest of justice** — strict adherence would cause injustice.",
        cases: [
          { name: "Gilford Motor Co. v. Horne (1933)", point: "Company formed to evade non-compete clause was sham — veil lifted, injunction granted against both." },
          { name: "Smith, Stone & Knight v. Birmingham (1939)", point: "Subsidiary merely agent of parent — parent entitled to compensation as real occupier." },
          { name: "Sir Dinshaw Petit v. CIT (1927)", point: "Companies formed to avoid income tax — veil lifted, income taxed in individual's hands." },
          { name: "Daimler Co. v. Continental Tyre (1916)", point: "WWI: company registered in England but all shares held by Germans — treated as enemy company." },
          { name: "Jones v. Lipman (1962)", point: "Property transferred to company to avoid specific performance — company was device and sham." },
          { name: "State of UP v. Renusagar Power (1988)", point: "SC: veil lifted where used to evade taxes, defeat convenience, protect fraud, or defend crime." },
          { name: "LIC v. Escorts Ltd. (1986)", point: "SC: veil may be lifted where statute permits or corporate form used for illegal/improper purpose." }
        ]},
      { title: "MoA, AoA, Ultra Vires & Indoor Management", type: "Part B: 10m",
        content: "**Memorandum of Association (MoA):**\nCharter/constitution of the company. Defines scope and powers. 6 Clauses:\n(1) **Name** — with 'Limited' or 'Private Limited'\n(2) **Registered Office** — state where situated\n(3) **Objects** — main objects, incidental objects, other objects. Most important clause.\n(4) **Liability** — limited to unpaid shares/guarantee\n(5) **Capital** — authorized share capital and division\n(6) **Association/Subscription** — subscribers' signatures\n\n**Doctrine of Ultra Vires:** Any act beyond objects clause is VOID. Cannot be ratified even by all shareholders unanimously. Purpose: protect shareholders (invested for specific objects) and creditors (gave credit based on stated objects). Consequences: contract void ab initio, no rights/obligations, directors may be personally liable.\n\n**Articles of Association (AoA):** Rules for INTERNAL management. Subordinate to MoA. Binds company and members as if signed by each member (Sec. 10).\n\n**Doctrine of Constructive Notice:** MoA and AoA are public documents filed with Registrar. Every person dealing with company is DEEMED to have notice of their contents. Ignorance is no excuse.\n\n**Doctrine of Indoor Management (Turquand's Rule):** Counterbalance to constructive notice. Third parties dealing with company entitled to ASSUME all internal procedures duly complied with. Need not inquire into internal affairs.\n\n**Exceptions to Turquand's Rule:** (1) Knowledge of irregularity, (2) No knowledge of articles at all, (3) Act ultra vires the company (not just directors), (4) Forgery (void ab initio).",
        cases: [
          { name: "Ashbury Railway v. Riche (1875)", point: "Leading case on ultra vires. Contract to finance railway beyond company objects — VOID, cannot be ratified." },
          { name: "Royal British Bank v. Turquand (1856)", point: "Lender entitled to assume borrowing resolution passed. Established indoor management rule." }
        ]},
      { title: "Directors — Powers, Duties & Legal Position", type: "Part B: 10m",
        content: "**Legal Position:** Directors occupy fiduciary position combining elements of: Agent (acts on behalf of company, their acts bind company), Trustee (trustees of company's money, property, powers — must act for company's benefit), Managing Partner (manage collectively through board meetings).\n\n**Powers (Sec. 179):** Board exercises ALL powers except those reserved for general meeting. Specific powers at board meetings only: make calls, authorize buy-back, issue securities, borrow money, invest funds, grant loans, approve financials, diversify business, approve amalgamation.\n\n**Duties (Sec. 166):**\n(1) Act in accordance with articles\n(2) Act in good faith for benefit of company, employees, shareholders, community, environment\n(3) Exercise due care, skill, diligence; independent judgment\n(4) Avoid conflict of interest\n(5) Not achieve undue gain for self/relatives\n(6) Not assign office (assignment void)\n\n**Disqualification (Sec. 164):** Unsound mind, undischarged insolvent, convicted of offence (imprisonment 6+ months in last 5 years), not obtained DIN, defaulting director of company not filing returns for 3 years.",
        cases: [
          { name: "Percival v. Wright (1902)", point: "Directors are trustees for company, not individual shareholders. No duty to disclose to individual shareholders." },
          { name: "Re City Equitable Fire Insurance (1925)", point: "Director must show reasonable care expected from person of his knowledge and experience." }
        ]},
      { title: "Shares, Debentures & Share Capital", type: "Part A: 3m / Part B: 10m",
        content: "**Share (Sec. 2(84)):** Interest of shareholder in company, measured by sum of money. Types: **Equity shares** (voting rights, dividend from profits, risk higher) and **Preference shares** (preferential dividend at fixed rate, preferential return of capital on winding up, limited/no voting).\n\n**Share Capital Types:** Authorized/Nominal (maximum allowed in MoA) → Issued (portion offered to public) → Subscribed (portion actually taken up) → Called-up (amount called by company) → Paid-up (amount actually paid).\n\n**Debentures (Sec. 2(30)):** Document acknowledging debt. Company is borrower, debenture holder is creditor. Types: Secured/Unsecured, Registered/Bearer, Redeemable/Irredeemable, Convertible/Non-convertible, Fixed charge (specific assets)/Floating charge (class of assets — crystallizes on default).\n\n**Shares vs Debentures:**\nShares = ownership capital | Debentures = borrowed capital/debt\nShareholder = member/owner | Debenture holder = creditor\nDividend (from profits, not guaranteed) | Interest (fixed, paid regardless)\nVoting rights | Generally no voting\nNot repayable during company life | Redeemable\nNot secured | May be secured by charge\nHigher risk | Lower risk\nPaid last in winding up | Paid before shareholders",
        cases: []},
      { title: "Winding Up — Types, Grounds & Liquidator", type: "Part B: 10m",
        content: "**Definition:** Process of bringing company's life to an end — realize assets, pay debts, distribute surplus.\n\n**Types:**\n**(1) By Tribunal (Compulsory — Sec. 271-274):** NCLT orders on grounds: (a) Special resolution by company, (b) Acts against sovereignty/integrity, (c) Fraudulent conduct, (d) Default in filing returns for 5 consecutive years, (e) Just and equitable.\n\n**(2) Voluntary:** (a) **Members' voluntary** — directors declare solvency (can pay debts in 3 years), special resolution, members appoint liquidator. (b) **Creditors' voluntary** — no solvency declaration, creditors participate in appointing liquidator.\n\n**(3) Subject to court supervision** — court supervises voluntary process.\n\n**Liquidator's Powers:** (a) Take custody of all property/assets, (b) Settle list of contributories, (c) Make calls, (d) Realize assets and distribute proceeds, (e) Institute/defend legal proceedings, (f) Carry on business for beneficial winding up, (g) Sell property, (h) Compromise claims.\n\n**Order of Payment:**\n(1) Costs of winding up\n(2) Preferential creditors (employees' wages 4 months, holiday wages, government dues 12 months)\n(3) Secured creditors (from charged assets)\n(4) Unsecured creditors\n(5) Preference shareholders\n(6) Equity shareholders",
        cases: [
          { name: "Ebrahimi v. Westbourne Galleries (1973)", point: "House of Lords: 'just and equitable' includes breach of understanding, exclusion from management, loss of confidence." }
        ]},
      { title: "Meetings, Quorum & Proxy", type: "Part B: 10m / Part C: 10m",
        content: "**Types of Meetings:**\n(1) **Board meetings** — directors' meetings.\n(2) **General meetings:**\n(a) **AGM (Sec. 96)** — annually, within 6 months of FY close, max 15 months gap. Business: adopt accounts, declare dividend, appoint auditors, appoint directors.\n(b) **EGM (Sec. 100)** — urgent business. Board can call, or on requisition of 10%+ of paid-up capital.\n\n**Quorum (Sec. 103):**\nPublic: 5 members (≤1000 members), 15 (1001-5000), 30 (>5000).\nPrivate: 2 members.\nNo quorum within **30 minutes** → adjourned to same day next week, same time, same place. At adjourned meeting, members present = quorum.\n\n**Proxy (Sec. 105):** Member appoints another to attend and vote on behalf. Need NOT be member. Instrument deposited **48 hours** before meeting. One proxy per member.\n\n**KEY RULE: When member personally attends, proxy stands AUTOMATICALLY REVOKED.** Principal's presence supersedes agent's authority.\n\n**Prospectus Issues:** Under Sec. 34-35, directors liable for misstatements. If minimum subscription not received within 30 days, all money returned within 15 days. If not returned within 78 days, directors jointly and severally liable.\n\n**Minimum subscription:** If company cannot get minimum subscription, it CANNOT allot shares. All money must be returned. Applicant can insist on return, not on allotment.",
        cases: []}
    ]
  },
  {
    id: "admin", title: "Administrative Law", subtitle: "Administrative agencies, judicial control, writs",
    color: "#185FA5", icon: "4",
    topics: [
      { title: "Rule of Law — Dicey's Theory & Indian Application", type: "Part A: 3m / Part B: 10m",
        content: "**Dicey's Three Principles:**\n\n**(1) Supremacy of Law:** No person shall be punished except for breach of law established in ordinary manner before ordinary courts. Excludes arbitrary or wide discretionary authority. Government must act according to law.\n\n**(2) Equality Before Law:** No person is above law. Every person, regardless of rank, subject to ordinary law administered by ordinary courts. No special courts for officials.\n\n**(3) Predominance of Legal Spirit:** Constitution is consequence of individual rights, not their source. Rights best protected by ordinary remedies in ordinary courts.\n\n**Criticism of Dicey:** (1) Ignored existence of administrative law in England, (2) Equality is simplistic — State has special immunities, (3) Modern governance requires discretionary powers, (4) Written constitutions have been effective.\n\n**Rule of Law in India:**\nArt. 14 — Equality before law and equal protection (Dicey's 2nd principle)\nArt. 21 — No deprivation of life/liberty except by procedure established by law (1st principle)\nArt. 19 — Fundamental freedoms with reasonable restrictions\nArt. 13 — Laws inconsistent with fundamental rights are void\nArt. 265 — No tax without authority of law\nArt. 226/32 — Writs for enforcement\n\n**Rule of Law as Basic Structure:** Cannot be amended under Art. 368 (Kesavananda Bharati).",
        cases: [
          { name: "ADM Jabalpur v. Shivkant Shukla (1976)", point: "SC restricted Art. 21 during Emergency. Justice Khanna's lone dissent upheld Rule of Law. Corrected by 44th Amendment." },
          { name: "Maneka Gandhi v. Union of India (1978)", point: "SC: 'procedure established by law' must be JUST, FAIR, and REASONABLE. Introduced substantive due process." },
          { name: "Kesavananda Bharati v. State of Kerala (1973)", point: "SC: Rule of Law, judicial review, separation of powers are BASIC STRUCTURE — cannot be amended." },
          { name: "Indira Gandhi v. Raj Narain (1975)", point: "Rule of Law and free elections are basic features of Constitution." },
          { name: "State of UP v. Raj Narain", point: "SC: Rule of Law is a basic feature. No one, including Prime Minister, is above law." }
        ]},
      { title: "Delegated Legislation — Definition & Judicial Control", type: "Part B: 10m",
        content: "**Definition:** Rules, regulations, bye-laws made by executive/administrative body under authority delegated by legislature through parent/enabling Act. Legislature frames policy broadly; delegatee fills in details.\n\n**Reasons for Growth:** (1) Parliamentary time pressure, (2) Technical complexity, (3) Flexibility — rules amended quickly, (4) Emergency powers, (5) Experimentation, (6) Unforeseen contingencies.\n\n**Essential Limitation: Legislature CANNOT delegate essential legislative function.** Must lay down legislative policy and guidelines. Only ancillary matters delegated.\n\n**Judicial Control:** Courts can invalidate on grounds:\n(1) **Substantive ultra vires** — beyond scope of parent Act\n(2) **Procedural ultra vires** — mandatory procedures not followed (consultation, publication, laying before Parliament)\n(3) **Unconstitutionality** — violates fundamental rights\n(4) **Unreasonableness** — manifestly arbitrary\n(5) **Mala fide** — improper purpose\n(6) **Sub-delegation** — delegatee further delegates without authority (delegatus non potest delegare)\n\n**Parliamentary Control:** (1) Laying on table (simple/negative/affirmative resolution), (2) Committee scrutiny, (3) Parliamentary questions and debates, (4) Ultimate control — amend/repeal parent Act.",
        cases: [
          { name: "In Re Delhi Laws Act (1951)", point: "SC (7-judge bench): Legislature can delegate provided it retains essential legislative function of laying down policy." },
          { name: "Hamdard Dawakhana v. Union of India (1960)", point: "SC struck down provision as excessive delegation — no guidelines or standards provided for determining 'objectionable' advertisements." }
        ]},
      { title: "Natural Justice — Both Pillars & Types of Bias", type: "Part B: 10m / Part C: 10m",
        content: "**Concept:** Fundamental rules of fair decision-making implied in every exercise of quasi-judicial and administrative power. No one should be condemned without fair hearing.\n\n**PILLAR 1: Audi Alteram Partem (Hear the other side)**\nNo person adversely affected without fair opportunity to present case.\nComponents:\n(1) **Right to notice** — adequate, specifying charges, time, place\n(2) **Right to know charges/evidence** — material relied upon\n(3) **Right to present case** — evidence, arguments, witnesses\n(4) **Right to cross-examine** witnesses against him\n(5) **Right to legal representation** — especially if presenting officer is legally trained\n(6) **Right to reasoned decision** — basis disclosed for challenge\n\n**PILLAR 2: Nemo Judex in Causa Sua (No judge in own cause)**\nDeciding authority must be free from bias. Even APPEARANCE of bias disqualifies. Justice must be done AND be SEEN to be done.\n\n**Types of Bias:**\n(1) **Personal bias** — relationship (friendship, enmity) with party\n(2) **Pecuniary bias** — financial interest, HOWEVER SMALL. Most serious — auto-disqualifies\n(3) **Subject matter bias** — direct involvement in subject matter\n(4) **Departmental bias** — department is both prosecutor and judge\n(5) **Preconceived notion bias** — prejudging the issue\n\n**Test:** Not whether authority WAS actually biased, but whether there is REASONABLE LIKELIHOOD of bias.\n\n**Exceptions to Natural Justice:** (1) Legislative action, (2) Emergency/urgent action, (3) Confidential/state security matters, (4) Academic evaluation, (5) Interim/preventive action (post-decisional hearing may be required), (6) Statute expressly excludes, (7) Where no prejudice (same decision would result).",
        cases: [
          { name: "Ridge v. Baldwin (1964)", point: "House of Lords revived natural justice. Chief Constable dismissed without hearing — void." },
          { name: "A.K. Kraipak v. Union of India (1970)", point: "SC: quasi-judicial/administrative distinction IRRELEVANT for natural justice. Committee member being candidate = bias." },
          { name: "Maneka Gandhi v. Union of India (1978)", point: "Passport impounded without hearing — deprivation of liberty must follow fair procedure including natural justice." },
          { name: "State of Orissa v. Dr. Binapani Dei (1967)", point: "SC: even reducing pension (administrative act) requires natural justice." },
          { name: "Pinochet Case (1999)", point: "Lord Hoffman disqualified for association with Amnesty International (party). House of Lords set aside OWN decision." },
          { name: "Manak Lal v. Dr. Prem Chand (1957)", point: "SC: if member of tribunal has personal interest/bias, proceedings vitiated even if bias didn't actually influence." },
          { name: "S. Parthasarathi v. State of AP (1973)", point: "SC: test is reasonable LIKELIHOOD of bias, not mere suspicion or actual bias." }
        ]},
      { title: "Writs — All Five Types (Art. 32 & 226)", type: "Part B: 10m",
        content: "**Art. 32:** SC writs — fundamental rights ONLY. Right to move SC is itself a fundamental right.\n**Art. 226:** HC writs — fundamental rights + ANY OTHER PURPOSE. Wider jurisdiction than SC.\n\n**1. Habeas Corpus ('Produce the body'):** Most powerful writ for personal liberty. Issued to produce detained person and examine legality of detention. Against BOTH State and private persons. Available even during Emergency (after 44th Amendment). Any person can file on behalf of detenu.\n\n**2. Mandamus ('We command'):** Positive command to perform public duty. Against: government departments, inferior courts, statutory bodies, public officials. CANNOT be issued against: President/Governor in official capacity, private individuals, legislative bodies. Petitioner must show: legal right exists, corresponding legal duty exists, duty is mandatory (not discretionary).\n\n**3. Certiorari ('To be certified'):** Quash order of inferior court/tribunal/quasi-judicial body that: (a) Acted without/in excess of jurisdiction, (b) Violated natural justice, (c) Error of law apparent on face of record. Curative — quashes order already made.\n\n**4. Prohibition ('To forbid'):** Similar to certiorari but PREVENTIVE. Issued to PREVENT inferior court from exceeding jurisdiction or violating natural justice. Before order is made (unlike certiorari which is after).\n\n**5. Quo Warranto ('By what authority'):** Challenge person holding PUBLIC OFFICE without legal authority. ANY person can file (not just aggrieved). Directed against holder of office, not appointing authority. Prevents usurpation of public office.",
        cases: [
          { name: "Kanu Sanyal v. District Magistrate (1973)", point: "SC: detenu need not be physically produced if court satisfied about detention." },
          { name: "S.P. Gupta v. Union of India (1982)", point: "SC expanded locus standi for mandamus — public-spirited persons can file (PIL)." },
          { name: "Hari Vishnu Kamath v. Syed Ahmad Ishaque (1955)", point: "SC: certiorari available only against judicial/quasi-judicial bodies, not purely administrative." },
          { name: "University of Mysore v. C.D. Govinda Rao (1965)", point: "Quo warranto issued when person holds public office without legal qualification." }
        ]},
      { title: "Government Liability — Sovereign & Non-Sovereign", type: "Part B: 10m / Part C: 10m",
        content: "**Art. 300:** Government may sue and be sued.\n\n**Sovereign functions:** Only State can perform — defence, law and order, administration of justice, legislation, diplomacy. Generally IMMUNE from tort liability.\n\n**Non-sovereign functions:** Commercial, welfare activities — running railways, hospitals, transport. State IS LIABLE like any private person.\n\n**Modern trend:** Narrowing sovereign immunity. In welfare state, distinction becoming increasingly irrelevant. State should be liable for most torts.\n\n**Fundamental rights violations:** State liable to pay compensation regardless of sovereign/non-sovereign distinction (Common Cause case).",
        cases: [
          { name: "P&O Steam Navigation v. Secretary of State (1861)", point: "Earliest case. Distinguished sovereign/non-sovereign. Government liable for negligent horse van driving (commercial — non-sovereign)." },
          { name: "State of Rajasthan v. Vidyawati (1962)", point: "Government servant negligently drove jeep, killed person. State liable — driving is not sovereign function." },
          { name: "Kasturilal v. State of UP (1965)", point: "Gold seized by police stolen by constable. State NOT liable — police custody is sovereign function. Widely CRITICIZED." },
          { name: "N. Nagendra Rao v. State of AP (1994)", point: "SC significantly NARROWED sovereign immunity. Only strictly sovereign functions (defence, foreign affairs) attract immunity." },
          { name: "Common Cause v. Union of India (1999)", point: "SC: sovereign immunity cannot deprive citizens of fundamental rights. State liable to pay compensation for FR violations." }
        ]},
      { title: "RTI Act, Prevention of Corruption & Tribunals", type: "Part B: 10m",
        content: "**RTI Act, 2005:** Ensures accountability and transparency. Citizens can: inspect works/documents, take notes/copies, take samples, obtain electronic information. PIO must respond within **30 days** (48 hours for life/liberty). First appeal to senior officer, second to Information Commission. Exemptions: sovereignty, security, cabinet papers, personal info, trade secrets. Proactive disclosure required (Sec. 4).\n\n**Prevention of Corruption Act, 1988:** Sec. 7: taking gratification other than legal remuneration. Sec. 13: criminal misconduct — habitual bribery, obtaining valuable things without consideration, disproportionate assets. **Sanction (Sec. 19):** Prior sanction of appointing authority required for prosecution. Tried by Special Judges.\n\n**Tribunals:** Quasi-judicial bodies for specialized areas. Art. 323A (Administrative Tribunals for service matters), Art. 323B (other matters). Key tribunals: CAT, ITAT, NGT, NCLT, DRT, Armed Forces Tribunal, Consumer Forums.\n\nAdvantages: speed, lower cost, expertise, flexibility.\nConcerns: independence, quality of members, exclusion of HC jurisdiction.",
        cases: [
          { name: "L. Chandra Kumar v. Union of India (1997)", point: "SC: judicial review power of HC (Art. 226/227) and SC (Art. 32) is BASIC STRUCTURE — cannot be excluded by tribunals." }
        ]}
    ]
  },
  {
    id: "interpretation", title: "Interpretation of Statutes", subtitle: "Rules of interpretation & principles of legislation",
    color: "#993556", icon: "5",
    topics: [
      { title: "Rules of Interpretation — Literal, Golden, Mischief, Harmonious", type: "Part B: 10m",
        content: "**1. Literal/Grammatical Rule (Primary Rule):** Words given plain, ordinary, grammatical meaning. If clear and unambiguous — give effect regardless of consequences. Court cannot add/subtract words. Starting point of all interpretation.\n\n**2. Golden Rule:** Modification of literal rule. Words given ordinary meaning UNLESS this leads to ABSURDITY, REPUGNANCY, or INCONSISTENCY. Court modifies meaning to avoid absurd result while staying as close as possible to literal meaning.\n\n**3. Mischief Rule (Heydon's Case, 1584):** Most flexible and purposive rule. Court examines: (i) What was common law before the Act? (ii) What was the mischief/defect? (iii) What remedy has Parliament prescribed? (iv) What is the true reason for the remedy? Court adopts construction that SUPPRESSES THE MISCHIEF and ADVANCES THE REMEDY.\n\n**4. Harmonious Construction:** When two provisions of SAME statute appear to conflict, court gives effect to BOTH by interpreting harmoniously. Neither provision rendered redundant.\n\n**Five principles (CIT v. Hindustan Bulk Carriers):** (i) Avoid head-on clash, (ii) Provision cannot defeat another unless impossible to reconcile, (iii) If irreconcilable — determine leading vs subordinate, (iv) One cannot nullify another, (v) Give effect to both.\n\n**5. Beneficial/Liberal Construction:** Remedial/welfare statutes construed liberally to advance their purpose. Used for social welfare legislation.\n\n**6. Strict Construction:** Penal and fiscal statutes construed strictly. Ambiguity resolved in favour of subject/accused.",
        cases: [
          { name: "Heydon's Case (1584)", point: "Origin of Mischief Rule. Barons of Exchequer laid down four questions for purposive interpretation." },
          { name: "Sussex Peerage Case (1844)", point: "House of Lords: duty is to interpret words legislature used. If clear — give effect regardless." },
          { name: "Grey v. Pearson (1857)", point: "Lord Wensleydale stated the Golden Rule: ordinary meaning unless absurdity." },
          { name: "CIT v. Hindustan Bulk Carriers (2003)", point: "SC laid down 5 principles of harmonious construction." },
          { name: "Venkataramana Devaru v. State of Mysore (1958)", point: "SC harmonized Art. 25(2)(b) and Art. 26(b) — temple entry and religious denomination rights." },
          { name: "Bengal Immunity Co. v. State of Bihar (1955)", point: "SC applied mischief rule to interpret scope of Art. 286." }
        ]},
      { title: "Ejusdem Generis", type: "Part A: 3m",
        content: "**Meaning:** 'Of the same kind.' When general words follow specific words, general words restricted to SAME CLASS as specific words. Specific words define the genus; general words limited to that genus.\n\n**Example 1:** 'Dogs, cats, and other animals' → other DOMESTIC animals (hamsters, birds), not wild animals (tigers).\n\n**Example 2:** 'Restaurants, cafes, canteens, and other establishments serving food' → food courts, mess halls — not hospitals or schools.\n\n**Conditions:** (1) Specific words must form a genus/category, (2) General words follow specific, (3) No contrary legislative intent, (4) Specific enumeration does not exhaust the genus.\n\n**When NOT applied:** (1) Specific words don't form a class, (2) General words used in independent sense, (3) Statute expressly provides wider meaning, (4) Specific enumeration exhausts entire genus.",
        cases: [
          { name: "Siddeshwari Cotton Mills v. UOI (1989)", point: "SC applied ejusdem generis — general words limited to same kind as specific." },
          { name: "Amar Chandra v. Collector of Excise (1972)", point: "SC: ejusdem generis is rule of construction, not rule of law — yields to contrary indications." }
        ]},
      { title: "Doctrine of Pith & Substance", type: "Part A: 3m / Part B: 10m",
        content: "**Purpose:** Determine TRUE NATURE AND CHARACTER of legislation when dispute about which List it falls under (Union List I / State List II / Concurrent List III under Seventh Schedule, Art. 246).\n\n**Test:** What is the DOMINANT/PRIMARY PURPOSE? If in its pith and substance (true nature) legislation falls within enacting legislature's competence, it is VALID even if it INCIDENTALLY ENCROACHES on matters in another list. Incidental encroachment does not invalidate.\n\n**Application:** Court looks at: (1) The substance/core of the legislation, (2) Its dominant purpose, (3) Its pith (real character), not its form or label. Surface encroachment ignored if true purpose is within legislature's domain.",
        cases: [
          { name: "State of Bombay v. F.N. Balsara (1951)", point: "Bombay Prohibition Act — in pith and substance about public health (State subject). Incidental effect on import/export doesn't invalidate." },
          { name: "Prafulla Kumar v. Bank of Commerce (1947)", point: "PC: Bengal Money Lenders Act about money lending (State) though incidentally affecting promissory notes (Union)." },
          { name: "Kartar Singh v. State of Punjab (1994)", point: "SC applied pith and substance to uphold TADA — in substance about terrorism/public order." }
        ]},
      { title: "Judicial Restraint & Judicial Activism", type: "Part A: 3m / Part B: 10m",
        content: "**Judicial Restraint:** Courts exercise self-limitation. Interpret law as written, defer to elected branches on policy. Based on: separation of powers, democratic legitimacy (judges not elected), institutional competence (courts not equipped for policy).\n\n**Judicial Activism:** Courts actively protect rights, creatively interpret law, fill legislative gaps. In India manifested through:\n\n**(1) PIL (Public Interest Litigation):** Relaxed locus standi — any public-spirited person can approach court on behalf of disadvantaged.\n\n**(2) Expansive interpretation of Art. 21:** Right to life expanded to include: right to livelihood (Olga Tellis), right to education, right to clean environment (MC Mehta), right to health, right to shelter, right to privacy, right to fair/speedy trial (Hussainara Khatoon), right to legal aid, right against custodial torture, right to live with dignity.\n\n**(3) Filling legislative gaps:** SC laid down guidelines having force of law until legislature acts (Vishakha guidelines on sexual harassment).\n\n**(4) Directive Principles read into Fundamental Rights.**\n\n**Criticism:** (1) Undermines separation of powers, (2) Courts lack policy expertise, (3) Judicial legislation without accountability, (4) Overburdening judiciary, (5) Selective activism.",
        cases: [
          { name: "Vishakha v. State of Rajasthan (1997)", point: "SC laid down guidelines on sexual harassment in absence of legislation — classic judicial activism." },
          { name: "MC Mehta v. Union of India", point: "SC directed closure of polluting industries, developed absolute liability principle for hazardous industries." },
          { name: "Hussainara Khatoon v. State of Bihar (1979)", point: "SC discovered undertrial prisoners jailed longer than max punishment — established right to speedy trial and free legal aid." },
          { name: "Olga Tellis v. BMC (1985)", point: "Right to livelihood is part of right to life under Art. 21. Pavement dwellers cannot be evicted without due process." },
          { name: "Antulay Case (1988)", point: "SC recognized right to speedy trial as fundamental right under Art. 21." }
        ]},
      { title: "Retrospective Operation of Statutes", type: "Part A: 3m / Part B: 10m",
        content: "**General Rule:** Every statute is PRIMA FACIE PROSPECTIVE unless expressly or by necessary implication made retrospective.\n\n**Constitutional Protection — Art. 20(1):** No conviction for act not offence when committed. No greater penalty than at time of act. This is a FUNDAMENTAL RIGHT — cannot be suspended even during Emergency.\n\n**Rationale:** (1) Affects vested rights, (2) Creates uncertainty, (3) Imposes unfair burden, (4) No punishment for act legal when committed.\n\n**When Retrospective ALLOWED:** (1) Express provision in statute, (2) Necessary implication from language, (3) Declaratory statutes (declare what law always was), (4) Curative/remedial statutes (cure defects), (5) Procedural statutes (change manner of enforcement, not substantive rights), (6) Taxation (if expressly stated, but must not be confiscatory).\n\n**When NOT ALLOWED:** (1) Penal statutes — Art. 20(1), (2) Taking away/impairing vested rights without clear language, (3) Imposing new obligations on past transactions, (4) Destroying accrued rights of action.",
        cases: [
          { name: "Zile Singh v. State of Haryana (2004)", point: "SC: general rule is prospectivity. Statute affecting vested rights not retrospective unless clear." },
          { name: "Hitendra Vishnu Thakur v. State of Maharashtra (1994)", point: "SC: 5 propositions — new offence can't be retrospective, procedural can, substantive rights can't." }
        ]},
      { title: "Strict Construction — Penal & Fiscal Statutes", type: "Part B: 10m",
        content: "**Penal Statutes:** Strictly construed IN FAVOUR OF ACCUSED. Ambiguity → benefit to accused. Cannot extend scope by analogy/implication. Every ingredient must be clearly established. Rationale: protection of personal liberty. Citizens must know in advance what is prohibited.\n\n**Fiscal/Taxation Statutes:** Strictly construed. NO TAX WITHOUT CLEAR AUTHORITY OF LAW. Ambiguity in charging section → benefit to taxpayer. State must bring case strictly within charging provision. Nothing read in, nothing implied.\n\n**However:** Strict ≠ narrowest possible. Give words natural meaning, don't stretch beyond reasonable. Also, EXEMPTION provisions in fiscal statutes construed LIBERALLY in favour of assessee.\n\n**Beneficial/Welfare Statutes:** Opposite approach — construed LIBERALLY to advance their protective purpose (e.g., Workmen's Compensation Act, consumer protection laws).",
        cases: [
          { name: "CIT v. Vegetable Products (1973)", point: "SC: if two interpretations possible, one favouring assessee MUST be adopted. Landmark on strict construction of tax statutes." },
          { name: "Commissioner of Sales Tax v. Modi Sugar Mills (1961)", point: "SC: nothing read in, nothing implied in tax statute. Look ONLY at language used." },
          { name: "Tolaram Relumal v. State of Bombay (1954)", point: "SC: words of penal statute must be followed even if result seems harsh." }
        ]},
      { title: "Presumptions in Statutory Interpretation", type: "Part B: 10m",
        content: "**(1) Against changes in common law:** Legislature presumed not to alter existing law unless expressly stated. If two interpretations possible — prefer one preserving common law.\n\n**(2) Against impairing obligations:** Statutes not interpreted to impair existing contracts/obligations/vested rights unless clear language.\n\n**(3) Against violation of international law:** Legislature presumed to conform with international obligations. Consistent interpretation preferred.\n\n**(4) Against ousting jurisdiction of courts:** Court jurisdiction not taken away unless express/necessary implication. Right to access courts is fundamental. Provisions excluding judicial review construed strictly.\n\n**(5) Of constitutionality:** Every statute presumed constitutional until proven otherwise. Burden on challenger. If two interpretations — prefer constitutional one.\n\n**(6) Of mens rea:** In criminal statutes, guilty mind presumed necessary unless expressly/impliedly excluded. Strict/absolute liability offences are exceptions.\n\n**(7) Against retrospectivity:** Prospective unless otherwise stated.\n\n**(8) Against absurdity:** Legislature doesn't intend absurd/unreasonable results. Literal interpretation leading to absurdity → court departs from literal rule.",
        cases: [
          { name: "State of MP v. G.S. Dall & Flour Mills (1991)", point: "SC: in absence of express exclusion, mens rea is essential ingredient of every statutory offence." }
        ]},
      { title: "Repugnancy, Preamble & Problem Questions", type: "Part A: 3m / Part C: 10m",
        content: "**Doctrine of Repugnancy (Art. 254):** When State law repugnant to Central law on Concurrent List subject → Central law prevails, State law void to extent of repugnancy. Exception: State law with President's assent prevails in that State.\n\n**Tests for Repugnancy:** (1) Direct conflict — impossible to obey both, (2) Same field — Central law intended to be exhaustive, (3) Implicit inconsistency — Central law covers field so completely, no room for State law.\n\n**Preamble:** Not part of statute but aids interpretation. Shows legislative intent and purpose. Cannot override clear provisions but helps resolve ambiguity.\n\n**Doctrine of Eclipse:** Pre-constitutional laws inconsistent with fundamental rights are not dead but merely eclipsed. If the inconsistency is removed (by constitutional amendment), the law revives.\n\n**PROBLEM: Sugarcane & Green Vegetables** — State law exempts 'Green Vegetables' from tax. Sugarcane farmer claims exemption.\n**Answer:** Exemption does NOT apply. Apply COMMON PARLANCE TEST — 'Green Vegetables' means spinach, beans, peas etc. Sugarcane is a cash crop, not a vegetable. Green leaves are incidental. No reasonable person would consider sugarcane a green vegetable. (Ramavatar Budhaiprasad v. ASTO)\n\n**PROBLEM: Retrospective Penal Law** — Law makes smoking in public offence from 1.4.2023. Person prosecuted for smoking on 31.3.2023.\n**Answer:** Prosecution INVALID. Art. 20(1) prohibits retrospective criminal legislation. Act was not offence when committed. Nullum crimen sine lege (no crime without law).\n\n**PROBLEM: Repeal & Re-enactment** — Act repealed and re-enacted. Rules under repealed Act?\n**Answer:** Under Sec. 24 of General Clauses Act, where an Act is repealed and re-enacted, rules made under repealed Act continue in force until superseded by new rules, if consistent with the re-enacted Act.",
        cases: [
          { name: "Deep Chand v. State of UP (1959)", point: "SC laid down three tests for determining repugnancy between Central and State laws." },
          { name: "M. Karunanidhi v. Union of India (1979)", point: "SC: repugnancy arises from direct inconsistency, Parliament occupying entire field, or Central law being complete code." },
          { name: "Ramavatar Budhaiprasad v. ASTO (1961)", point: "SC: in interpreting tax entries, common parlance test applies — terms understood in popular sense." }
        ]}
    ]
  }
];
