// NotebookLM page helpers — paste into the notebook tab's console (or inject via Claude in Chrome javascript_tool).
// Usage: await __loadPrompts('crpc'); await __gen('CR01TE'); __status(); await __rename('12:34','CR01TE'); await __menuClick('CR01TE','Download')
window.__rowOf=(dur)=>[...document.querySelectorAll('button[aria-label^="More"]')].map(b=>{let el=b;for(let k=0;k<6&&el;k++){el=el.parentElement;if(el&&/Deep dive/i.test(el.innerText))break;} return {b,el}}).filter(x=>x.el&&/Deep dive/i.test(x.el.innerText)).find(x=>x.el.innerText.includes(dur));
window.__menuClick=async(dur,label)=>{const r=__rowOf(dur); if(!r) return 'row not found'; ['pointerover','mouseover','mouseenter'].forEach(t=>r.el.dispatchEvent(new MouseEvent(t,{bubbles:true}))); r.b.click(); await new Promise(z=>setTimeout(z,600)); const m=[...document.querySelectorAll('[role=menuitem]')].find(e=>new RegExp(label).test(e.textContent)); if(!m) return 'no menu item '+label; m.click(); await new Promise(z=>setTimeout(z,600)); return 'clicked '+label};
window.__rename=async(dur,name)=>{const s=await __menuClick(dur,'Rename'); const inp=[...document.querySelectorAll('input[class*=artifact-title]')].find(i=>i.value.includes(dur)); if(!inp) return s+' / no input for '+dur; const setter=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set; inp.focus(); setter.call(inp,name); inp.dispatchEvent(new Event('input',{bubbles:true})); for(const t of ['keydown','keypress','keyup']) inp.dispatchEvent(new KeyboardEvent(t,{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true})); inp.dispatchEvent(new Event('change',{bubbles:true})); inp.blur(); await new Promise(z=>setTimeout(z,2000)); return 'renamed '+dur+' -> '+name};
window.__dlgEls=()=>{const ta=[...document.querySelectorAll('textarea')].find(t=>/focus on in this episode/i.test(t.getAttribute('aria-label')||t.placeholder||'')||/What should the AI hosts/.test((t.labels&&t.labels[0]||{}).textContent||'')); const dlg=[...document.querySelectorAll('[role=dialog]')].find(x=>/Customi[sz]e Audio Overview/.test(x.innerText)); const cb=dlg?dlg.querySelector('[role=combobox]'):[...document.querySelectorAll('[role=combobox]')].find(c=>/English|తెలుగు/.test(c.textContent)); const gen=[...document.querySelectorAll('button')].find(b=>/^\s*Generate( now)?\s*$/.test(b.textContent)); const later=[...document.querySelectorAll('button')].find(b=>/Generate later/.test(b.textContent)); return {ta,cb,gen,later,dlg}};
window.__setPrompt=(v)=>{const {ta}=__dlgEls(); if(!ta) return 'no textarea'; const setter=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set; ta.focus(); setter.call(ta,v); ta.dispatchEvent(new Event('input',{bubbles:true})); ta.dispatchEvent(new Event('change',{bubbles:true})); return 'set '+ta.value.length+' chars'};
window.__openDlg=async()=>{const leaf=[...document.querySelectorAll('span,div,button')].find(e=>e.children.length===0 && e.textContent.trim()==='Audio Overview'); let el=leaf; for(let k=0;k<5&&el;k++){ if(el.tagName==='BUTTON'||el.getAttribute('role')==='button') break; el=el.parentElement; } (el||leaf).click(); await new Promise(z=>setTimeout(z,1500)); const d=__dlgEls(); return {ta:!!d.ta, cb:d.cb?d.cb.textContent.trim():null, gen:!!d.gen, later:!!d.later}};
window.__status=()=>{const t=document.body.innerText; return {generating:(t.match(/Generating Audio Overview/g)||[]).length, scheduled:(t.match(/Scheduled for[^\n]*/g)||[]).length, limit:(t.match(/[^\n]*(daily Audio Overview limit|usage limit|Come back later)[^\n]*/i)||[null])[0], rows:(t.match(/[^\n]+\n\d\d:\d\d · Deep [Dd]ive/g)||[]).map(x=>x.replace('\n',' | ')).slice(0,6)}};
window.__loadPrompts=async(subj)=>{window.__P=window.__P||{}; for(const l of ['te','en']){ const r=await fetch(`https://padala.law/sem5-pipeline/prompts/${subj}_${l}.json?v=${Date.now()}`); const arr=await r.json(); arr.forEach(x=>{__P[x.tag]=x.prompt;}); } return Object.keys(__P).length;};
window.__langNow=()=>{const {cb}=__dlgEls(); if(!cb) return null; if(cb.tagName==='SELECT') return cb.selectedOptions[0]?cb.selectedOptions[0].textContent.trim():cb.value; return cb.textContent.trim().slice(0,20)};
window.__selectLang=async(want)=>{const {cb}=__dlgEls(); if(!cb) return 'no combobox'; const re=want==='te'?/తెలుగు/:/^\s*English\s*$/; if(cb.tagName==='SELECT'){ const o=[...cb.options].find(o=>re.test(o.textContent)); if(!o) return 'no option'; cb.value=o.value; cb.dispatchEvent(new Event('input',{bubbles:true})); cb.dispatchEvent(new Event('change',{bubbles:true})); await new Promise(z=>setTimeout(z,600)); return __langNow(); } cb.click(); await new Promise(z=>setTimeout(z,800)); const opt=[...document.querySelectorAll('[role=option]')].find(o=>re.test(o.textContent)); if(!opt) return 'no option'; opt.click(); await new Promise(z=>setTimeout(z,800)); return __langNow(); };
window.__gen=async(tag)=>{ if(!__P[tag]) return 'no prompt '+tag; if(!__dlgEls().ta){ await __openDlg(); } let d=__dlgEls(); if(!d.ta) return 'dialog did not open'; for(let i=0;i<8&&!d.cb;i++){ await new Promise(z=>setTimeout(z,500)); d=__dlgEls(); } if(!d.cb) return 'no language combobox'; const want=/TE$/.test(tag)?'te':'en'; const cur=__langNow()||''; if(want==='te' && !/తెలుగు/.test(cur)) await __selectLang('te'); if(want==='en' && !/^English$/.test(cur)) await __selectLang('en'); const s=__setPrompt(__P[tag]); d=__dlgEls(); const lang=__langNow(); const btn=d.gen||d.later; if(!btn) return 'no Generate/later button; '+s; const mode=d.gen?'now':'later'; btn.click(); await new Promise(z=>setTimeout(z,3000)); const st=__status(); return `${tag}: ${lang} ${mode} sched=${st.scheduled} gen=${st.generating} ${st.limit||''}`; };
window.__selectSource=async(name)=>{ const all=[...document.querySelectorAll('[aria-label^="Select "]')]; let out=[]; for(const cb of all){ const want=cb.getAttribute('aria-label')==='Select '+name; if(cb.checked!==want){ cb.click(); await new Promise(z=>setTimeout(z,500)); } out.push(cb.getAttribute('aria-label')+'='+cb.checked); } return out; };
'helpers loaded';
